-- HR SaaS System - Supabase Initial Setup
-- Execute this script in Supabase SQL Editor

-- 1. Create basic company for testing
INSERT INTO companies (id, name, domain, subscription_plan, subscription_status, settings, industry, size_category, country, timezone) VALUES 
('00000000-0000-0000-0000-000000000001', '测试公司', 'demo', 'pro', 'active', '{}', 'Technology', 'small', 'China', 'Asia/Shanghai')
ON CONFLICT (domain) DO NOTHING;

-- 2. Create basic roles
INSERT INTO roles (id, company_id, name, description, is_system_role) VALUES 
('10000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'admin', '系统管理员', true),
('10000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'hr', 'HR专员', true),
('10000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000001', 'recruiter', '招聘专员', true),
('10000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000001', 'manager', '部门经理', true),
('10000000-0000-0000-0000-000000000005', '00000000-0000-0000-0000-000000000001', 'employee', '员工', true)
ON CONFLICT (company_id, name) DO NOTHING;

-- 3. Create basic departments
INSERT INTO departments (id, company_id, name, description, is_active) VALUES 
('20000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', '技术部', '技术研发部门', true),
('20000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', '人事部', '人力资源部门', true),
('20000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000001', '产品部', '产品管理部门', true),
('20000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000001', '设计部', '设计部门', true)
ON CONFLICT DO NOTHING;

-- 4. Create basic positions
INSERT INTO positions (id, company_id, title, description, department_id, level, salary_range_min, salary_range_max, is_active) VALUES 
('30000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', '前端工程师', '负责前端开发工作', '20000000-0000-0000-0000-000000000001', 'mid', 200000, 400000, true),
('30000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', '后端工程师', '负责后端开发工作', '20000000-0000-0000-0000-000000000001', 'mid', 250000, 450000, true),
('30000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000001', 'HR专员', '负责人力资源管理', '20000000-0000-0000-0000-000000000002', 'mid', 150000, 300000, true),
('30000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000001', '产品经理', '负责产品规划', '20000000-0000-0000-0000-000000000003', 'mid', 200000, 400000, true),
('30000000-0000-0000-0000-000000000005', '00000000-0000-0000-0000-000000000001', 'UI设计师', '负责界面设计', '20000000-0000-0000-0000-000000000004', 'mid', 180000, 350000, true)
ON CONFLICT DO NOTHING;

-- 5. Create test user data (will be linked when users sign up)
-- Note: User IDs will be generated by Supabase Auth when users register

-- 6. Create some test jobs
INSERT INTO jobs (id, company_id, title, description, requirements, location, employment_type, salary_range_min, salary_range_max, status) VALUES 
('40000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', '高级前端工程师', 
'我们正在寻找一位经验丰富的前端工程师加入我们的技术团队。您将负责开发和维护我们的用户界面，与设计师和后端工程师密切合作。', 
'- 3年以上前端开发经验\n- 精通React、Vue或Angular\n- 熟悉HTML、CSS、JavaScript\n- 有TypeScript经验优先', 
'北京', 'full_time', 25000, 40000, 'published'),

('40000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', '产品经理', 
'负责产品规划、需求分析和项目管理，与技术团队协作推进产品开发。', 
'- 3年以上产品管理经验\n- 熟悉用户研究和数据分析\n- 有B端产品经验优先\n- 良好的沟通协调能力', 
'上海', 'full_time', 20000, 35000, 'published'),

('40000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000001', 'UI/UX设计师', 
'负责产品界面设计和用户体验优化，制定设计规范和风格指南。', 
'- 3年以上UI/UX设计经验\n- 精通Figma、Sketch等设计工具\n- 有移动端和Web端设计经验\n- 理解用户体验设计原理', 
'深圳', 'full_time', 18000, 30000, 'draft')
ON CONFLICT DO NOTHING;

-- 7. Basic permissions setup (simplified)
INSERT INTO permissions (id, name, module, description) VALUES 
('50000000-0000-0000-0000-000000000001', 'jobs.view', 'recruitment', '查看职位信息'),
('50000000-0000-0000-0000-000000000002', 'jobs.create', 'recruitment', '创建职位'),
('50000000-0000-0000-0000-000000000003', 'jobs.edit', 'recruitment', '编辑职位'),
('50000000-0000-0000-0000-000000000004', 'candidates.view', 'recruitment', '查看候选人'),
('50000000-0000-0000-0000-000000000005', 'candidates.create', 'recruitment', '创建候选人'),
('50000000-0000-0000-0000-000000000006', 'users.view', 'employee', '查看员工信息'),
('50000000-0000-0000-0000-000000000007', 'users.create', 'employee', '创建员工'),
('50000000-0000-0000-0000-000000000008', 'system.admin', 'system', '系统管理权限')
ON CONFLICT (name) DO NOTHING;

-- Success message
SELECT 'Database initialization completed successfully!' as status;